using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace VidlyApp
{
    public class RouteConfig
    {
        public static void RegisterRoutes(RouteCollection routes)
        {
            routes.IgnoreRoute("{resource}.axd/{*pathInfo}");
            routes.MapMvcAttributeRoutes();


            //routes.MapRoute(
            //    "MoviesByReleaseDate", //Name of our route within the context of this file
            //    "movies/released/{year}/{month}", //Format of the URL mapping to this route

            //    //Anonymous objects are declared below. They're direcly derived from Object, with their 
            //    //type name invisibly generated by the compiler and therefore unavailable at source-code level.
            //    //Anonymous types contian one or more read-only properties, like the examples below.
            //    //Particularly useful in "select" clause of a query expression, as they store only the necessary values in read-only form.
            //    new { controller = "Movies", action = "ByReleaseDate" }, //Controller & Action being called by this route
            //    new { year = @"2015|2016", month = @"\d{2}" }); //Contraints being applied to the variable parameters

            routes.MapRoute(
                name: "Default",
                url: "{controller}/{action}/{id}",
                defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional }
            );
        }
    }
}
